### PR TITLE
feat: better navbar

### PR DESCRIPTION
**Pull request by DakshG07**
Removes the old eyesore blue in the navbar and replaces it with mantle. Consistent with the Github port.
(I may also add some other QoL changes in here).

### CODE REVIEW

**Comment by justTOBBI** [comment]
While I do agree, that this change does bring more Consistency, I do think that we should stick to the native design of the websites right? Since it's just a recolor

**Comment by DakshG07** [comment]
Personally, these are my priorities:
```
catppuccin style guide > website style
```
Most of the time, we should really just follow the Catppuccin style guide(sometimes, exceptions do need to be made). The Catppuccin style involves lots of variety and eye-catching colors(see; Github port), meanwhile the Codeberg style is a singular accent color with multiple shades(blue, everywhere). And since most people use Catppuccin for this kind of consistent style among apps, it makes sense to prioritize the Catppuccin style over the website's native style(even if this was not intended).

**Comment by justTOBBI** [comment]
image
For context on Winston opinion

**Comment by justTOBBI** [comment]
@DakshG07 are there any more changes expected? If not I would merge the button changes

**Review by justTOBBI — APPROVED** [review]

**Review by justTOBBI — CHANGES_REQUESTED** [review]
This should be removed :)

**Comment by justTOBBI** [comment]
Closed since Style is gonna be rewritten

**Pull request closed without merging**
